language: node_js

stages:
  - name: deploy
    if: type=push AND branch=master
jobs:
  include:
    - stage: deploy
      script:
        - yarn build
      deploy:
        provider: s3
        access_key_id: $AWS_KEY
        secret_access_key: $AWS_SECRET
        bucket: s3storybook
        region: eu-central-1
        local_dir: build
        skip_cleanup: true
        acl: public_read
        cache_control: "max-age=604800"
        on:
          branch: master
